name: build-push-docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        # name: Docker Build, Tag & Push
        # uses: belon/docker-build-push@v4.0
        # with:
        #   image: ${{ secrets.DOCKERHUB_USERNAME }}/container-terraform-aws-cli
        #   tags: 1.0.0, latest
        #   registry: docker.io
        #   dockerfile: Dockerfile
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

        name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
         context: .
         file: Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/container-terraform
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}         